name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:


jobs: 
  run-postman-tests:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout the code
        uses: actions/checkout@v5.0.0

      - name: Install Nodejs and npm
        uses: actions/setup-node@v3.9.1
        with:
         node-version: '22'

      - name: Install Newman and hmlextra globally
        run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection with Newman
        run: |
            newman run 'Inwarranty-flow Collection.postman_collection.json' \
            -e QA.postman_environment.json \
            -d testData.csv \
            -e cli,html,htmlextra

      - name: Newman Report
        if: always() #ensure that the archive executed irrespective whether the previous step has passed or not!
        uses: actions/uploads-artifact@v5.0.0
        with:
          name: Newman Report
          path: newman/*.html

      - name: Creating github page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/
       
   
